<?xml version="1.0" encoding="utf-8"?><Database Name="EcommerceDb" Class="EcommerceDataContext" AccessModifier="Internal" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=EcommerceDb;Integrated Security=True" SettingsObjectName="Ecommerce.Data.Properties.Settings" SettingsPropertyName="EcommerceDbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CartItems" Member="CartItems">
    <Type Name="CartItem">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShoppingCartId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_CartItem" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" />
      <Association Name="ShoppingCart_CartItem" Member="ShoppingCart" ThisKey="ShoppingCartId" OtherKey="Id" Type="ShoppingCart" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Categorys" Member="Categories">
    <Type Name="Category">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Category_Product" Member="Products" ThisKey="Id" OtherKey="Categoryid" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Images" Member="Images">
    <Type Name="Image">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ProductId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Product_Image" Member="Product" ThisKey="ProductId" OtherKey="Id" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Categoryid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ShortDescription" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LongDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Association Name="Product_CartItem" Member="CartItems" ThisKey="Id" OtherKey="ProductId" Type="CartItem" />
      <Association Name="Product_Image" Member="Images" ThisKey="Id" OtherKey="ProductId" Type="Image" />
      <Association Name="Category_Product" Member="Category" ThisKey="Categoryid" OtherKey="Id" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ShoppingCart" Member="ShoppingCarts">
    <Type Name="ShoppingCart">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Association Name="ShoppingCart_CartItem" Member="CartItems" ThisKey="Id" OtherKey="ShoppingCartId" Type="CartItem" />
    </Type>
  </Table>
  <Function Name="dbo.GetProductsAndImage" Method="GetProductsAndImage" AccessModifier="Internal">
    <ElementType Name="GetProductsAndImageResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Categoryid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Money NOT NULL" CanBeNull="false" />
      <Column Name="ShortDescription" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LongDescription" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>